parameters:
    lyssal.entity_administrator_manager.class: Lyssal\Doctrine\OrmBundle\Administrator\EntityAdministratorManager

services:
    _defaults:
        autowire: true

    _instanceof:
        Lyssal\Doctrine\Orm\Administrator\EntityAdministratorInterface:
            tags: ['lyssal.entity_administrator']

    lyssal.entity_administrator_manager:
        class: '%lyssal.entity_administrator_manager.class%'
        public: true
        calls:
            - [ 'addEntityAdministrators', [ !tagged lyssal.entity_administrator ] ]

    Lyssal\Doctrine\OrmBundle\Administrator\EntityAdministratorManager:
        alias: 'lyssal.entity_administrator_manager'
