parameters:
    lyssal.doctrine.orm.entity_manager.class: Lyssal\Doctrine\Orm\Manager\EntityManager
    lyssal.entity_manager.class: Lyssal\Doctrine\OrmBundle\Manager\EntityManager

services:
    _defaults:
        autowire: true

    lyssal.entity_manager:
        class: '%lyssal.entity_manager.class%'
        public: true

    Lyssal\Doctrine\OrmBundle\Manager\EntityManager:
        alias: 'lyssal.entity_manager'
